[2025-06-04T06:08:25.886+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: auto_pull_dags_from_github.git_pull_latest_dags manual__2025-06-04T06:08:24.473784+00:00 [queued]>
[2025-06-04T06:08:25.897+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: auto_pull_dags_from_github.git_pull_latest_dags manual__2025-06-04T06:08:24.473784+00:00 [queued]>
[2025-06-04T06:08:25.898+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-04T06:08:25.910+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): git_pull_latest_dags> on 2025-06-04 06:08:24.473784+00:00
[2025-06-04T06:08:25.915+0000] {standard_task_runner.py:60} INFO - Started process 177 to run task
[2025-06-04T06:08:25.918+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'auto_pull_dags_from_github', 'git_pull_latest_dags', 'manual__2025-06-04T06:08:24.473784+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/auto_pull_dags.py', '--cfg-path', '/tmp/tmpb6gm9c77']
[2025-06-04T06:08:25.921+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask git_pull_latest_dags
[2025-06-04T06:08:25.994+0000] {task_command.py:423} INFO - Running <TaskInstance: auto_pull_dags_from_github.git_pull_latest_dags manual__2025-06-04T06:08:24.473784+00:00 [running]> on host 76ddeb3967d1
[2025-06-04T06:08:26.051+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='aswin.b@sganlytics.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='auto_pull_dags_from_github' AIRFLOW_CTX_TASK_ID='git_pull_latest_dags' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T06:08:24.473784+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T06:08:24.473784+00:00'
[2025-06-04T06:08:26.053+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-04T06:08:26.054+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dags && git pull origin main']
[2025-06-04T06:08:26.063+0000] {subprocess.py:86} INFO - Output:
[2025-06-04T06:08:26.065+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: git: command not found
[2025-06-04T06:08:26.066+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-06-04T06:08:26.075+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-06-04T06:08:26.081+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=auto_pull_dags_from_github, task_id=git_pull_latest_dags, execution_date=20250604T060824, start_date=20250604T060825, end_date=20250604T060826
[2025-06-04T06:08:26.095+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 32 for task git_pull_latest_dags (Bash command failed. The command returned a non-zero exit code 127.; 177)
[2025-06-04T06:08:26.132+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-04T06:08:26.147+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
