[2025-06-04T15:23:11.106+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_etl_pipeline.transform manual__2025-06-04T15:22:36.470152+00:00 [queued]>
[2025-06-04T15:23:11.117+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_etl_pipeline.transform manual__2025-06-04T15:22:36.470152+00:00 [queued]>
[2025-06-04T15:23:11.118+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-04T15:23:11.132+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform> on 2025-06-04 15:22:36.470152+00:00
[2025-06-04T15:23:11.138+0000] {standard_task_runner.py:60} INFO - Started process 7055 to run task
[2025-06-04T15:23:11.142+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'demo_etl_pipeline', 'transform', 'manual__2025-06-04T15:22:36.470152+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/sample_etl_dag.py', '--cfg-path', '/tmp/tmpghk08wh2']
[2025-06-04T15:23:11.145+0000] {standard_task_runner.py:88} INFO - Job 57: Subtask transform
[2025-06-04T15:23:11.223+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_etl_pipeline.transform manual__2025-06-04T15:22:36.470152+00:00 [running]> on host 036d21481f2d
[2025-06-04T15:23:11.314+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='aswin.b@sganlytics.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T15:22:36.470152+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T15:22:36.470152+00:00'
[2025-06-04T15:23:11.317+0000] {logging_mixin.py:188} INFO - ⚠️ Simulating failure in transform step
[2025-06-04T15:23:11.318+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sample_etl_dag.py", line 21, in transform
    raise Exception("Simulated failure for demo purposes")
Exception: Simulated failure for demo purposes
[2025-06-04T15:23:11.332+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=demo_etl_pipeline, task_id=transform, execution_date=20250604T152236, start_date=20250604T152311, end_date=20250604T152311
[2025-06-04T15:23:11.348+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2025-06-04T15:23:11.349+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-06-04T15:23:13.247+0000] {email.py:281} INFO - Sent an alert email to ['aswin.b@sganlytics.com']
[2025-06-04T15:23:15.177+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 57 for task transform (Simulated failure for demo purposes; 7055)
[2025-06-04T15:23:15.223+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-04T15:23:15.251+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
