[2025-06-04T15:05:00.683+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: auto_pull_dags_from_github.git_pull_latest_dags manual__2025-06-04T15:04:58.718274+00:00 [queued]>
[2025-06-04T15:05:00.694+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: auto_pull_dags_from_github.git_pull_latest_dags manual__2025-06-04T15:04:58.718274+00:00 [queued]>
[2025-06-04T15:05:00.695+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-04T15:05:00.710+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): git_pull_latest_dags> on 2025-06-04 15:04:58.718274+00:00
[2025-06-04T15:05:00.715+0000] {standard_task_runner.py:60} INFO - Started process 6762 to run task
[2025-06-04T15:05:00.719+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'auto_pull_dags_from_github', 'git_pull_latest_dags', 'manual__2025-06-04T15:04:58.718274+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/auto_pull_dags.py', '--cfg-path', '/tmp/tmp03386h3b']
[2025-06-04T15:05:00.722+0000] {standard_task_runner.py:88} INFO - Job 52: Subtask git_pull_latest_dags
[2025-06-04T15:05:00.794+0000] {task_command.py:423} INFO - Running <TaskInstance: auto_pull_dags_from_github.git_pull_latest_dags manual__2025-06-04T15:04:58.718274+00:00 [running]> on host 036d21481f2d
[2025-06-04T15:05:00.877+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='aswin.b@sganlytics.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='auto_pull_dags_from_github' AIRFLOW_CTX_TASK_ID='git_pull_latest_dags' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T15:04:58.718274+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T15:04:58.718274+00:00'
[2025-06-04T15:05:00.880+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-04T15:05:00.881+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dags && git pull origin main']
[2025-06-04T15:05:00.893+0000] {subprocess.py:86} INFO - Output:
[2025-06-04T15:05:00.896+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: git: command not found
[2025-06-04T15:05:00.897+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-06-04T15:05:00.909+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-06-04T15:05:00.914+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=auto_pull_dags_from_github, task_id=git_pull_latest_dags, execution_date=20250604T150458, start_date=20250604T150500, end_date=20250604T150500
[2025-06-04T15:05:00.926+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 52 for task git_pull_latest_dags (Bash command failed. The command returned a non-zero exit code 127.; 6762)
[2025-06-04T15:05:00.972+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-04T15:05:00.992+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
