[2025-06-04T09:00:02.145+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: auto_pull_dags_from_github.git_pull_latest_dags scheduled__2025-06-04T08:00:00+00:00 [queued]>
[2025-06-04T09:00:02.154+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: auto_pull_dags_from_github.git_pull_latest_dags scheduled__2025-06-04T08:00:00+00:00 [queued]>
[2025-06-04T09:00:02.157+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-04T09:00:02.176+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): git_pull_latest_dags> on 2025-06-04 08:00:00+00:00
[2025-06-04T09:00:02.183+0000] {standard_task_runner.py:60} INFO - Started process 1424 to run task
[2025-06-04T09:00:02.190+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'auto_pull_dags_from_github', 'git_pull_latest_dags', 'scheduled__2025-06-04T08:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/auto_pull_dags.py', '--cfg-path', '/tmp/tmp6yu1jtek']
[2025-06-04T09:00:02.197+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask git_pull_latest_dags
[2025-06-04T09:00:02.270+0000] {task_command.py:423} INFO - Running <TaskInstance: auto_pull_dags_from_github.git_pull_latest_dags scheduled__2025-06-04T08:00:00+00:00 [running]> on host 036d21481f2d
[2025-06-04T09:00:02.330+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='aswin.b@sganlytics.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='auto_pull_dags_from_github' AIRFLOW_CTX_TASK_ID='git_pull_latest_dags' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-04T08:00:00+00:00'
[2025-06-04T09:00:02.332+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-04T09:00:02.334+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dags && git pull origin main']
[2025-06-04T09:00:02.344+0000] {subprocess.py:86} INFO - Output:
[2025-06-04T09:00:02.348+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: git: command not found
[2025-06-04T09:00:02.348+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-06-04T09:00:02.357+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-06-04T09:00:02.360+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=auto_pull_dags_from_github, task_id=git_pull_latest_dags, execution_date=20250604T080000, start_date=20250604T090002, end_date=20250604T090002
[2025-06-04T09:00:02.371+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 45 for task git_pull_latest_dags (Bash command failed. The command returned a non-zero exit code 127.; 1424)
[2025-06-04T09:00:02.403+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-04T09:00:02.419+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
